# Generated by Django 4.2.4 on 2023-08-15 20:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="не более 200 символов",
                        max_length=200,
                        verbose_name="Введите заголовок поста",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="не более 5000 символов",
                        max_length=5000,
                        null=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="blog_cards/%Y/%m/%d"),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes_post",
                    models.ManyToManyField(
                        blank=True,
                        related_name="post_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
                (
                    "saves_posts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_posts_save",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сохранённые посты пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Создать пост",
                "verbose_name_plural": "Создать посты",
            },
        ),
    ]
