# Generated by Django 4.2.4 on 2023-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_cards/%Y/%m/%d"
            ),
        ),
    ]
