# Generated by Django 4.2.4 on 2023-09-25 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="не более 1000 символов",
                max_length=1000,
                null=True,
            ),
        ),
    ]
