# Generated by Django 4.2.4 on 2023-10-08 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="saved_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="catalog_products_save",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сохранённые товары пользователя",
            ),
        ),
    ]
