# Generated by Django 4.2.4 on 2023-10-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="stock",
        ),
    ]
