# Generated by Django 4.2.4 on 2023-10-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_quantity_orderitem_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="stock",
            new_name="quantity",
        ),
    ]
